#!/usr/bin/env node
// Generates everything `perf web` needs OUTSIDE the project:
//   <gen>/web/perf-probe.js        the probe as one classic script (served as /__perf/probe.js)
//   <gen>/webpack.perf.config.js   wraps the project's webpack config (webpack, Create React App)
//   <gen>/vite.perf.config.mjs     wraps the project's Vite config
// Builds go to <cache>/web-build/<variant>; the project's own build folder is never touched.
//
//   node prepare-web.mjs --repo <path> --out <gen> --cache <cache dir> --variant <id> --port <app port>
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { buildComponentIndex } from './component-index.mjs';
import { projectConfig, pickVariant, inProject } from './config.mjs';

const PERF_PORT = 8099;
const toolRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const args = process.argv.slice(2);
const option = name => {
  const index = args.indexOf(`--${name}`);
  return index === -1 ? undefined : args[index + 1];
};

const repoRoot = path.resolve(option('repo') ?? process.cwd());
const out = path.resolve(option('out'));
const cacheDir = path.resolve(option('cache'));
const project = projectConfig(repoRoot);
if (!project || project.kind !== 'web') {
  console.error(`perf: ${repoRoot} is not set up as a web project (perf init)`);
  process.exit(2);
}
const variant = pickVariant(project, option('variant'));
const port = Number(option('port') || project.port || 8080);
const variantKey = variant.id.replace(/[^\w.-]+/g, '_');
const webDir = path.join(out, 'web');
const outDir = path.join(cacheDir, 'web-build', variantKey);
const statsFile = path.join(outDir, 'perf-stats.json');

function write(file, content) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content);
}

// The commit plus a hash of the uncommitted changes (same as lib/prepare.mjs), so a before/after
// comparison can tell two builds apart.
function buildStamp() {
  const git = gitArgs => {
    try {
      return execFileSync('git', ['-C', repoRoot, ...gitArgs], { maxBuffer: 256 * 1024 * 1024, stdio: ['ignore', 'pipe', 'ignore'] }).toString();
    } catch {
      return '';
    }
  };
  const sourceDirs = project.sourceDirs?.length ? project.sourceDirs.filter(dir => !dir.startsWith('node_modules')) : ['src'];
  const head = git(['rev-parse', '--short', 'HEAD']).trim();
  const changes = git(['diff', 'HEAD', '--', ...sourceDirs, 'package.json']);
  const untracked = git(['ls-files', '--others', '--exclude-standard', ...sourceDirs]);
  const hash = crypto.createHash('sha1').update(changes).update(untracked).digest('hex').slice(0, 10);
  return { builtAt: Date.now(), commit: head || null, code: `${head || 'nogit'}+${hash}`, variant: variant.id };
}

// One classic script: a tiny module wrapper around the tracker and the probe, with the config inline.
function probeScript() {
  const module = file => fs.readFileSync(path.join(toolRoot, 'probe', file), 'utf8');
  const probeConfig = { build: buildStamp(), components: [...buildComponentIndex(repoRoot).keys()] };
  return `/* perf-tool web probe — generated by perf web for ${path.basename(repoRoot)} (${variant.id}); not part of the app. */
(function () {
  'use strict';
  if (window.__perfProbe) return;
  window.__PERF_PROBE_CONFIG__ = ${JSON.stringify(probeConfig)};
  var modules = {};
  modules['./leakTracker'] = { exports: {} };
  (function (module, exports) {
${module('leakTracker.js')}
  })(modules['./leakTracker'], modules['./leakTracker'].exports);
  var require = function (name) {
    if (modules[name]) return modules[name].exports;
    throw new Error('perf probe: unknown module ' + name);
  };
  (function (module, exports, require) {
${module('webProbe.js')}
  })({ exports: {} }, {}, require);
})();
`;
}

const probeFile = path.join(webDir, 'perf-probe.js');
write(probeFile, probeScript());

const generatedWebpack = path.join(out, 'webpack.perf.config.js');
const generatedVite = path.join(out, 'vite.perf.config.mjs');
const options = {
  repoRoot,
  outDir,
  cacheDir: path.join(cacheDir, 'webpack-cache'),
  cacheName: `perf-${variantKey}`,
  statsFile,
  probeFile,
  port,
  perfPort: PERF_PORT
};

if (project.bundler === 'vite') {
  const userConfig = inProject(repoRoot, project.bundlerConfig);
  write(
    generatedVite,
    `// Generated by perf-tool for ${repoRoot} (${variant.id}).
import { withPerfProbe } from ${JSON.stringify(path.join(toolRoot, 'lib/vite-perf.mjs'))};
${userConfig ? `import userConfig from ${JSON.stringify(userConfig)};` : 'const userConfig = {};'}
export default withPerfProbe(userConfig, ${JSON.stringify(options, null, 2)});
`
  );
} else {
  const source =
    project.bundler === 'cra'
      ? `craConfig(${JSON.stringify(repoRoot)}, { port: ${port} })`
      : `require(${JSON.stringify(inProject(repoRoot, project.bundlerConfig ?? 'webpack.config.js'))})`;
  write(
    generatedWebpack,
    `// Generated by perf-tool for ${repoRoot} (${variant.id}).
const { withPerfProbe, craConfig } = require(${JSON.stringify(path.join(toolRoot, 'lib/webpack-perf.cjs'))});
module.exports = withPerfProbe(${source}, ${JSON.stringify(
      { ...options, configFiles: [generatedWebpack, path.join(toolRoot, 'lib/webpack-perf.cjs')] },
      null,
      2
    )});
`
  );
}

console.log(`Prepared the web probe build for ${variant.id} in ${out} (build output: ${outDir})`);
