#!/usr/bin/env node
// Generates everything a probe build needs OUTSIDE the project:
//   <gen>/bundle/       entry file + probe + host/component lists (Metro watch folder)
//   <gen>/metro.config.js   wraps the project's Metro config (BUNDLE_CONFIG / Gradle bundleConfig)
//   <gen>/perf.xcconfig      -xcconfig override that force-loads the native iOS probe into the app
//   <gen>/init.gradle        Gradle init script pointing the release bundle at the probe entry
//   <gen>/ios/<sdk>/libPerfProbe.a
//
//   node prepare.mjs --repo <path> --out <gen> [--ios-sdk iphoneos|iphonesimulator]

import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { buildComponentIndex } from './component-index.mjs';
import { projectConfig } from './config.mjs';

const PORT = 8099;
const IOS_MIN_VERSION = '15.1';
const toolRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const args = process.argv.slice(2);
const option = name => {
  const index = args.indexOf(name);
  return index === -1 ? undefined : args[index + 1];
};

const repoRoot = path.resolve(option('--repo') ?? process.cwd());
const out = path.resolve(option('--out'));
const iosSdk = option('--ios-sdk');
const envFile = option('--env-file');
const bundleDir = path.join(out, 'bundle');
// Saved by the setup page; the defaults are the usual React Native layout.
const project = projectConfig(repoRoot) ?? {};
const entry = path.join(repoRoot, project.entry ?? 'index');
const metroConfig = path.join(repoRoot, project.metroConfig ?? 'metro.config.js');
const envModule = project.envKind === 'module' && project.envModule ? path.join(repoRoot, project.envModule) : null;
const sourceDirs = project.sourceDirs?.length ? project.sourceDirs.filter(dir => !dir.startsWith('node_modules')) : ['src'];

function probeHosts() {
  const addresses = Object.values(os.networkInterfaces())
    .flat()
    .filter(item => item && item.family === 'IPv4' && !item.internal)
    .map(item => item.address);
  const hostName = os.hostname().replace(/\.local$/, '');
  return [...new Set(['localhost', `${hostName}.local`, ...addresses])];
}

// Identifies the code inside a probe build: the commit plus a hash of the uncommitted changes, so
// an automatic "after" run can tell when the app on the phone is still the "before" build.
function buildStamp() {
  const git = args => {
    try {
      return execFileSync('git', ['-C', repoRoot, ...args], { maxBuffer: 256 * 1024 * 1024 }).toString();
    } catch {
      return '';
    }
  };
  const head = git(['rev-parse', '--short', 'HEAD']).trim();
  const changes = git(['diff', 'HEAD', '--', ...sourceDirs, `${path.relative(repoRoot, entry)}.*`, 'App.*', 'package.json']);
  const untracked = git(['ls-files', '--others', '--exclude-standard', ...sourceDirs]);
  const hash = crypto.createHash('sha1').update(changes).update(untracked).digest('hex').slice(0, 10);
  return { builtAt: Date.now(), commit: head || null, code: `${head || 'nogit'}+${hash}` };
}

function write(file, content) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content);
}

const hosts = probeHosts();
const navigationRef = path.join(repoRoot, project.navigationRef ?? 'src/navigator/navigationRef.js');

write(path.join(bundleDir, 'hosts.json'), JSON.stringify(hosts));
write(path.join(bundleDir, 'build.json'), JSON.stringify(buildStamp()));
write(path.join(bundleDir, 'components.json'), JSON.stringify([...buildComponentIndex(repoRoot).keys()]));
fs.copyFileSync(path.join(toolRoot, 'probe/perfProbe.js'), path.join(bundleDir, 'perfProbe.js'));
write(
  path.join(bundleDir, 'index.perf.js'),
  [
    '// Generated by ~/perf-tool. The probe must run before React loads.',
    fs.existsSync(navigationRef)
      ? `global.__perfProbeNavigationRef = () => require(${JSON.stringify(navigationRef)}).navigationRef;`
      : '',
    "require('./perfProbe');",
    `require(${JSON.stringify(entry)});`,
    ''
  ].join('\n')
);

write(
  path.join(out, 'metro.config.js'),
  `// Generated by ~/perf-tool for ${repoRoot}
const { withPerfProbe } = require(${JSON.stringify(path.join(toolRoot, 'lib/metro-perf.js'))});
module.exports = withPerfProbe(require(${JSON.stringify(metroConfig)}), {
  repoRoot: ${JSON.stringify(repoRoot)},
  bundleDir: ${JSON.stringify(bundleDir)},
  envModule: ${JSON.stringify(envModule)},
  envFile: ${JSON.stringify(envFile && envModule ? path.resolve(envFile) : null)}
});
`
);

// Applied to every target by xcodebuild, but only app targets (WRAPPER_EXTENSION = app) pick up
// the flag; pod targets are static frameworks and are not linked with OTHER_LDFLAGS anyway.
write(
  path.join(out, 'perf.xcconfig'),
  `// Generated by ~/perf-tool
PERF_PROBE_LDFLAGS_app = -force_load "${path.join(out, 'ios')}/$(PLATFORM_NAME)/libPerfProbe.a" -framework QuartzCore -framework UIKit
OTHER_LDFLAGS = $(inherited) $(PERF_PROBE_LDFLAGS_$(WRAPPER_EXTENSION))
`
);

write(
  path.join(out, 'init.gradle'),
  `// Generated by ~/perf-tool: points the release JS bundle at the probe entry for this build only.
allprojects {
  plugins.withId('com.android.application') {
    plugins.withId('com.facebook.react') {
      project.extensions.getByName('react').with {
        entryFile.set(file(${JSON.stringify(path.join(bundleDir, 'index.perf.js'))}))
        bundleConfig.set(file(${JSON.stringify(path.join(out, 'metro.config.js'))}))
      }
    }
  }
}
`
);

if (iosSdk) {
  const libDir = path.join(out, 'ios', iosSdk);
  fs.mkdirSync(libDir, { recursive: true });
  write(
    path.join(libDir, 'PerfProbeHosts.h'),
    `static NSString *const kPerfProbeHosts = @"${hosts.join(',')}";\nstatic const int kPerfProbePort = ${PORT};\n`
  );
  const target = iosSdk === 'iphonesimulator' ? `arm64-apple-ios${IOS_MIN_VERSION}-simulator` : `arm64-apple-ios${IOS_MIN_VERSION}`;
  const sdkPath = execFileSync('xcrun', ['--sdk', iosSdk, '--show-sdk-path'], { encoding: 'utf8' }).trim();
  const object = path.join(libDir, 'PerfProbeNative.o');
  execFileSync('xcrun', [
    '--sdk', iosSdk, 'clang', '-c', '-O2', '-fobjc-arc', '-fmodules',
    '-target', target, '-isysroot', sdkPath, '-I', libDir,
    path.join(toolRoot, 'ios/PerfProbeNative.m'), '-o', object
  ], { stdio: 'inherit' });
  execFileSync('xcrun', ['libtool', '-static', '-o', path.join(libDir, 'libPerfProbe.a'), object], { stdio: 'inherit' });
}

console.log(`Prepared probe build files in ${out}`);
